-- POLITICA DE BACKUP

-- 1 DA MANHA - FULL (DATABASE WITH INT)
-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)
-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - FULL (DATABASE WITH DIFFERENTIAL)
-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)
-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)

SELECT DISTINCT [data] FROM tb_nota order by [data] DESC

CREATE TABLE tb_controle_backups 
(ID INTEGER, NOME VARCHAR(100), NUMERO_NOTAS INTEGER);

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (1, 'BACKUP FULL 1 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP DATABASE dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH INIT;

-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (2, 'BACKUP INCREMENTAL 4 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;


-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (3, 'BACKUP INCREMENTAL 6 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (4, 'BACKUP INCREMENTAL 8 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;


-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (5, 'BACKUP DIFFERENTIAL 9 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups 

BACKUP DATABASE dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH DIFFERENTIAL;

-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (6, 'BACKUP INCREMENTAL 10 AM', (SELECT COUNT(*) FROM tb_nota)); 
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (7, 'BACKUP INCREMENTAL 12 AM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups 

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (8, 'BACKUP INCREMENTAL 2 PM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups;

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 2 DA TARDE - FULL (DATABASE WITH DIFFERENTIAL)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (9, 'BACKUP DIFFERENTIAL 2 PM', (SELECT COUNT(*) FROM tb_nota)); 
SELECT * FROM tb_controle_backups;

BACKUP DATABASE dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH DIFFERENTIAL;

-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (10, 'BACKUP INCREMENTAL 3 PM', (SELECT COUNT(*) FROM tb_nota)); 
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (11, 'BACKUP INCREMENTAL 5 PM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups 

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (12, 'BACKUP INCREMENTAL 7 PM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'

INSERT INTO tb_controle_backups VALUES (13, 'BACKUP INCREMENTAL 9 PM', (SELECT COUNT(*) FROM tb_nota));
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;

SELECT * FROM tb_controle_backups
