SELECT * FROM tb_controle_backups

RESTORE HEADERONLY FROM
DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'

USE MASTER;
ALTER DATABASE dbVendas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE dbVendas;

RESTORE HEADERONLY FROM
DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'

RESTORE DATABASE dbVendas FROM DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 1, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 9, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 10, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK = 'F:\SQL\DATA\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 11, RECOVERY;
