CREATE DATABASE [Vendas]
 ON  PRIMARY ( 
	 NAME = N'Vendas', 
	 FILENAME = N'F:\SQL\DATA\ARQUIVO_DADOS\Vendas.MDF', 
	 SIZE = 10MB, 
	 MAXSIZE = 50MB, 
	 FILEGROWTH = 5MB 
 )
 LOG ON ( 
	 NAME = N'VendasLOG', 
	 FILENAME = N'F:\SQL\DATA\LOG_TRANSACOES\VendasLOG.LDF', 
	 SIZE = 10, 
	 MAXSIZE = 50, 
	 FILEGROWTH = 5
 );

USE Vendas

CREATE TABLE PRODUTOS (
    CODIGO VARCHAR(10) PRIMARY KEY, 
    DESCRITOR VARCHAR(100), 
    SABOR VARCHAR(50), 
    TAMANHO VARCHAR(50), 
    EMBALAGEM VARCHAR(50), 
    PRECO_LISTA FLOAT
)

CREATE TABLE VENDEDORES (
    MATRICULA VARCHAR(5) PRIMARY KEY, 
    NOME VARCHAR(100), 
    BAIRRO VARCHAR(50), 
    COMISSAO FLOAT, 
    DATA_ADMISSAO DATE, 
    FERIAS BIT
)

CREATE TABLE CLIENTES ( 
	CPF VARCHAR(11) PRIMARY KEY, 
	NOME VARCHAR(100), 
	ENDERECO VARCHAR(100), 
	BAIRRO VARCHAR(50), 
	CIDADE VARCHAR(50), 
	ESTADO VARCHAR(50), 
	CEP VARCHAR(8), 
	DATA_NASCIMENTO DATE, 
	IDADE INTEGER, 
	GENERO VARCHAR(1), 
	LIMITE_CREDITO FLOAT, 
	VOLUME_COMPRA FLOAT, 
	PRIMEIRA_COMPRA BIT
)

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR(5) PRIMARY KEY, 
    DATA_VENDA DATE, 
    CPF VARCHAR(11) FOREIGN KEY REFERENCES CLIENTES (CPF), 
    MATRICULA VARCHAR(5) FOREIGN KEY REFERENCES VENDEDORES (MATRICULA), 
    IMPOSTO FLOAT, 
);

CREATE TABLE TABELA_DE_ITENS_VENDIDOS (
	NUMERO VARCHAR(5),
	CODIGO VARCHAR(10),
	QUANTIDADE FLOAT,
	PRECO FLOAT,
	PRIMARY KEY (NUMERO, CODIGO),
	FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO),
	FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO)
);

RESTORE DATABASE SUCOS_FRUTAS FROM DISK = 'F:\SQL\DATA\BACKUP\SUCOS_FRUTAS.BAK' WITH RECOVERY;

-- Importando dados de outro banco de dados

INSERT PRODUTOS 
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

INSERT CLIENTES
SELECT CPF, NOME, ENDERECO_1 ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO DATA_NASCIMENTO, 
	   IDADE, GENERO, LIMITE_DE_CREDITO LIMITE_CREDITO, VOLUME_DE_COMPRA VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES

-- Importando dados de csv

CREATE TABLE #TempVendedores (
    [MATRICULA] VARCHAR(5),
    [NOME] NVARCHAR(100),
    [COMISSAO] FLOAT,
    [DATA_ADMISSAO] DATE,
    [FERIAS] BIT,
    [BAIRRO] NVARCHAR(50)
);

BULK INSERT #TempVendedores
FROM 'F:\SQL\DATA\CSV\Vendedores.csv'
WITH (
    FIELDTERMINATOR = ';',
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
    TABLOCK
);

INSERT VENDEDORES
SELECT MATRICULA, NOME, BAIRRO, COMISSAO, DATA_ADMISSAO, FERIAS
FROM #TempVendedores

DROP TABLE #TempVendedores;

-- Dessincronizando tabelas (para poder fazer a sincronização)

UPDATE PRODUTOS SET PRECO_LISTA *= .5;

-- Sincronizando tabelas

UPDATE P SET P.PRECO_LISTA = S.PRECO_DE_LISTA
FROM PRODUTOS P JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS S 
ON P.CODIGO = S.CODIGO_DO_PRODUTO;

-- Dessincronizando tabelas novamente

UPDATE PRODUTOS SET PRECO_LISTA *= .5;

-- Sincronizando tabelas com MERGE

MERGE PRODUTOS P USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS S
ON P.CODIGO = S.CODIGO_DO_PRODUTO WHEN MATCHED THEN 
UPDATE SET P.PRECO_LISTA = S.PRECO_DE_LISTA;

-- Conferindo Preços

SELECT P.PRECO_LISTA TABELA_NOVA, S.PRECO_DE_LISTA TABELA_ANTIGA 
FROM PRODUTOS P JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS S 
ON P.CODIGO = S.CODIGO_DO_PRODUTO;

-- Dessincronizando Número de registros

INSERT PRODUTOS VALUES ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50)

-- Sinconizando Produtos

DELETE FROM PRODUTOS WHERE CODIGO NOT IN 
( SELECT CODIGO_DO_PRODUTO FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS )