USE SUCOS_VENDAS

-- Excluindo e Criando tabelas

DROP TABLE IF EXISTS TABELA_TESTE;

IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL
	DROP TABLE TABELA_TESTE

IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL
	CREATE TABLE TABELA_TESTE (ID VARCHAR(10))


-- Verificando o Dia da Semana

DECLARE @DIA_SEMANA VARCHAR(20), @DIAS INT

SET @DIAS = 5
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @DIAS, GETDATE()))
PRINT @DIA_SEMANA

IF (@DIA_SEMANA = 'Sunday' or @DIA_SEMANA = 'Saturday')
	PRINT 'Fim de Semana'
ELSE
	PRINT 'Dia Útil'

-- Corrigindo idade caso errada

DECLARE @CPF VARCHAR(15), @DATA_NASCIMENTO DATE, @IDADE_TABELA INT, @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE_TABELA = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE()) - 
        CASE 
            WHEN MONTH(@DATA_NASCIMENTO) > MONTH(GETDATE()) OR 
                 (MONTH(@DATA_NASCIMENTO) = MONTH(GETDATE()) AND DAY(@DATA_NASCIMENTO) > DAY(GETDATE())) 
            THEN 1 
            ELSE 0 
        END;

IF @IDADE <> @IDADE_TABELA
	UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF;

-- Verificando Crédito

DECLARE @BAIRRO VARCHAR(20);

SET @BAIRRO = 'Água Santa';

IF (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO) >= 50000
	PRINT 'LIMITE ESTOROU'
ELSE
	PRINT 'LIMITE VÁLIDO'