USE SUCOS_VENDAS

DECLARE @CPF VARCHAR(50), @NOME VARCHAR(100), @DATA_NASCIMENTO DATE, @IDADE INT

SET @CPF = '19290992743';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT 'Nome: ' + @NOME + CHAR(13) + CHAR(10) + CONCAT('Data: ', @DATA_NASCIMENTO) + CHAR(13) + CHAR(10) + CONCAT('Idade: ', @IDADE)