USE SUCOS_VENDAS

DECLARE @CPF VARCHAR(11), @NOME VARCHAR(100), @I INT, @TOTAL_CLIENTES INT
DECLARE @MES INT, @ANO INT, @TOTAL_VENDAS FLOAT
DECLARE @TABELA TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, TOTAL_VENDAS FLOAT);

SET @MES = 11;
SET @ANO = 2016;

SELECT @TOTAL_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES]
SET @I = 1

WHILE @I <= @TOTAL_CLIENTES
BEGIN

	WITH C AS (SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS LINHA, * FROM [TABELA DE CLIENTES])
	SELECT @CPF = CPF, @NOME = NOME FROM C WHERE LINHA = @I
	
	SELECT @TOTAL_VENDAS = SUM(INF.QUANTIDADE * INF.PREÇO)
	FROM [NOTAS FISCAIS] NF JOIN [ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO
	WHERE NF.CPF = @CPF AND YEAR(NF.[DATA]) = @ANO AND MONTH(NF.[DATA]) = @MES;

	INSERT INTO @TABELA VALUES (@CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS);

	SET @I += 1 
END

SELECT * FROM @TABELA