USE SUCOS_VENDAS

-- Declaração Cursor

DECLARE CURSOR1 CURSOR FOR SELECT TOP 5 NOME FROM [TABELA DE CLIENTES]

-- Abre Cursor

OPEN CURSOR1

-- Execução de códigos

DECLARE @NOMES VARCHAR(200)
FETCH NEXT FROM CURSOR1 INTO @NOMES
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOMES
	FETCH NEXT FROM CURSOR1 INTO @NOMES
END

-- Fechando Cursor

CLOSE CURSOR1

-- Liberando recursos (Exclui Cursor)

DEALLOCATE CURSOR1


-- Cursor para mostrar nome e Endereço completos

DECLARE CURSOR2 CURSOR FOR
	SELECT NOME, CONCAT([ENDERECO 1] + ', ', BAIRRO + ', ', CIDADE + ' - ', ESTADO) ENDERECO
	FROM [TABELA DE CLIENTES]

DECLARE @NOME VARCHAR(100), @ENDERECO VARCHAR(MAX)

OPEN CURSOR2

FETCH NEXT FROM CURSOR2 INTO @NOME, @ENDERECO

WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT @NOME + ' ' + @ENDERECO
	FETCH NEXT FROM CURSOR2 INTO @NOME, @ENDERECO
END

CLOSE CURSOR2

DEALLOCATE CURSOR2

-- Cursor para pegar um cliente aleatório

DECLARE CURSOR3 CURSOR FOR SELECT CPF FROM [TABELA DE CLIENTES]

DECLARE @CLIENTE VARCHAR(12), @ALEATORIO INT, @COUNTER INT

SET @ALEATORIO = CAST(FLOOR(((SELECT COUNT(*) FROM [TABELA DE CLIENTES])) * RAND() + 1) AS INT)
SET @COUNTER = 1

OPEN CURSOR3

FETCH NEXT FROM CURSOR3 INTO @CLIENTE

WHILE @COUNTER < @ALEATORIO
BEGIN
    FETCH NEXT FROM CURSOR3 INTO @CLIENTE
    SET @COUNTER += 1
END

CLOSE CURSOR3

DEALLOCATE CURSOR3

SELECT @CLIENTE, @ALEATORIO