USE SUCOS_VENDAS;

-- Função de Números Aleatórios

CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS ALEATORIO

CREATE FUNCTION NumeroAleatorio (@MIN INT, @MAX INT)
RETURNS INT
BEGIN
	RETURN CAST(FLOOR((@MAX - @MIN + 1) * (SELECT * FROM VW_ALEATORIO) + @MIN) AS INT);
END

PRINT DBO.NumeroAleatorio(1,2)

-- Função para calcular faturamento

CREATE FUNCTION Faturamento (@NUM AS INT)
RETURNS FLOAT
AS
BEGIN
	RETURN (
		SELECT SUM(QUANTIDADE * [PREÇO])
		FROM [ITENS NOTAS FISCAIS] 
		WHERE NUMERO = @NUM
	)
END

SELECT NUMERO, dbo.Faturamento(NUMERO) FATURAMENTO
FROM [NOTAS FISCAIS]

-- Função para verificar uma sequencia de notas

CREATE FUNCTION VerificaNota (@MIN INT, @MAX INT)
RETURNS @TABELA TABLE 
(
    NUM INT, 
    [STATUS] BIT, 
    FATURAMENTO FLOAT
)
BEGIN
	WHILE @MIN <= @MAX
	BEGIN
		IF (SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @MIN) > 0
			INSERT @TABELA VALUES (@MIN, 1, dbo.Faturamento(@MIN))
		ELSE
			INSERT @TABELA VALUES (@MIN, 0, NULL)
		SET @MIN += 1
	END

	RETURN
END

SELECT * FROM dbo.VerificaNota(95, 105)

-- Função para retornar notas fiscais de um cliente

CREATE FUNCTION NotasClientes (@CPF VARCHAR(11))
RETURNS TABLE
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT COUNT(*) FROM dbo.NotasClientes((SELECT TOP 1 CPF FROM [TABELA DE CLIENTES]))

-- Função para mostrar Endereço Completo

CREATE FUNCTION Endereco (@ENDERECO VARCHAR(100), @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50), @ESTADO VARCHAR(2))
RETURNS VARCHAR(202)
BEGIN
	RETURN CONCAT(@ENDERECO + ', ', @BAIRRO + ', ', @CIDADE + ', ', @ESTADO) 
END 

SELECT CPF, dbo.Endereco([ENDERECO 1], BAIRRO, CIDADE, ESTADO) FROM [TABELA DE CLIENTES]

-- Alterando a Função para mostrar Endereço Completo

ALTER FUNCTION Endereco (@ENDERECO VARCHAR(100), @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50), @ESTADO VARCHAR(2))
RETURNS VARCHAR(202)
BEGIN
	RETURN CONCAT(@ENDERECO + ', ', @BAIRRO + ', ', @CIDADE + ' - ', @ESTADO) 
END 

SELECT CPF, dbo.Endereco([ENDERECO 1], BAIRRO, CIDADE, ESTADO) FROM [TABELA DE CLIENTES]

-- Excluindo a Função para mostrar Endereço Completo

DROP FUNCTION dbo.Endereco

DROP FUNCTION IF EXISTS dbo.Endereco

IF OBJECT_ID('Endereco', 'FN') IS NOT NULL
	DROP FUNCTION [dbo].[Enderecoscompleto3]